version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-webhook
    ports:
      - 4000:4000
    env_file:
      - ./backend/.env
    restart: unless-stopped
